- README.md
- output/data/results.csv
- output/statistics/results.csv
- services/DataCollectorImpl.groovy
- services/ModifiedLine.groovy
- src/main/FileManager.groovy
Esse PR pretende separar linhas removidas de linhas modificadas e adicionadas.
Agora, o arquivo gerado pelo DataCollector possui essas colunas (negrito para novidade):
nome-do-projeto | merge commit | full-qualified name (classe) | método | linhas modificadas por left | **linhas removidas por left** | linhas modificadas por right | **linhas removidas por right**
> Deletion lines list

- README.md
- output/data/results.csv
- src/main/FileManager.groovy
- src/main/MiningFramework.groovy
- src/main/ProcessRunner.groovy
- src/main/Project.groovy
- src/main/arguments/ArgsParser.groovy
- src/main/arguments/Arguments.groovy
- src/main/exception/InvalidArgsException.groovy
- src/main/interfaces/CommitFilter.groovy
- src/main/interfaces/DataCollector.groovy
- src/main/interfaces/StatisticsCollector.groovy
- src/main/project/MergeCommit.groovy
- src/main/project/Project.groovy
- src/main/script/MiningFramework.groovy
- src/main/util/FileManager.groovy
- src/main/util/ProcessRunner.groovy
- src/services/CommitFilterImpl.groovy
- src/services/DataCollectorImpl.groovy
- src/services/MiningModule.groovy
- src/services/ModifiedLine.groovy
- src/services/ModifiedMethod.groovy
- src/services/StatisticsCollectorImpl.groovy
Esse PR pretende trazer mudanças de código para torna-lo mais legível.
Mudanças:
- Extrações de método e simplificação de algoritmos.
- **Mudança na estrutura do projeto.**
Essa mudança, feita a partir do commit c0f0238 , torna a estrutura do código mais organizada. Também torna mais simples a execução do programa (apenas `src` precisa estar no classpath) e a importação do projeto em IDEs.
> Refatoração

- README.md
- output/data/results.csv
- src/main/FileManager.groovy
- src/main/MiningFramework.groovy
- src/main/ProcessRunner.groovy
- src/main/Project.groovy
- src/main/arguments/ArgsParser.groovy
- src/main/arguments/Arguments.groovy
- src/main/exception/InvalidArgsException.groovy
- src/main/interfaces/CommitFilter.groovy
- src/main/interfaces/DataCollector.groovy
- src/main/interfaces/StatisticsCollector.groovy
- src/main/project/MergeCommit.groovy
- src/main/project/Project.groovy
- src/main/script/MiningFramework.groovy
- src/main/util/FileManager.groovy
- src/main/util/ProcessRunner.groovy
- src/services/CommitFilterImpl.groovy
- src/services/DataCollectorImpl.groovy
- src/services/MiningModule.groovy
- src/services/ModifiedLine.groovy
- src/services/ModifiedMethod.groovy
- src/services/StatisticsCollectorImpl.groovy
Esse PR pretende transformar as listas de linhas deletadas por left e por right como listas de duplas, onde o primeiro elemento do par se refere a exata linha deletada da base, enquanto o segundo se refere a linha do merge onde a deletada deveria estar.
- Algoritmo de buscar métodos modificados refeito para se tornar mais legível.
- Os campos "left deletions" e "right deletions" da planilha mostram listas de duplas.
É certo que esse PR causará conflitos de merge com os outros PRs. Pra facilitar a revisão, apenas os dois últimos commits foram introduzidos com esse PR.
> Lista de duplas de linhas deletadas

- src/main/exception/UnexpectedOutputException.groovy
- src/main/project/Project.groovy
- src/services/DataCollectorImpl.groovy
- src/services/StatisticsCollectorImpl.groovy
Esse PR tem o objetivo de trazer um tratamento maior de exceções e recursos.
- Todos os BufferedReaders são agora apropriadamente fechados e possuem um try-catch para denunciar erros de leitura.
- Tratamento de exceção em algumas execuções de comandos git (todas as inerentes ao estudo, pertencentes à classe `Project`), para o caso onde a saída do comando não é a esperada.
> Tratamento de exceção e recursos

- src/main/arguments/ArgsParser.groovy
- src/main/interfaces/CommitFilter.groovy
- src/main/interfaces/ExperimentalDataCollector.groovy
- src/main/interfaces/StatisticsCollector.groovy
- src/main/script/MiningFramework.groovy
- src/main/util/FileManager.groovy
- src/services/CommitFilterImpl.groovy
- src/services/ExperimentalDataCollectorImpl.groovy
- src/services/MiningModule.groovy
- src/services/ModifiedLine.groovy
- src/services/StatisticsCollectorImpl.groovy
Eu tomei como base os commits que João já tinha enviado na outra pull request, porque ele mudou a estrutura dos arquivos e isso ia causar inconsistências.
Essa pull request reliza as seguintes tarefas:
* Mover Main para começo da classe
* Parse imprimindo Help não está claro
* Substituir ArrayList no start para tipo Abstrato
* Renomear collectData para collectExperimentalData
* Renomear classe DataCollector para ExperimentalDataCollector
* Trocar de classe pra interface DataCollector, StatisticsCollector e CommitFilter
* Adicionar links no StatisticsCollector
* Adicionar data na mensagem de commit
* Renomear FileManager.createDataFiles para createExperimentalDataFiles
* Criar método argumentsSize em no ArgsParser
> Refatoração Geral

- src/main/util/FileManager.groovy
> Mudar FileManager pra fazer menos operações de IO

- scripts/parse_to_soot.py
- src/services/OutputProcessorImpl.groovy
- src/services/StatisticsCollectorImpl.groovy
> Adiciona script que separa informações sobre linhas modificadas para pastas dos commits

- scripts/fetch_jars.py
- src/main/app/MiningWorker.groovy
- src/services/BuildRequester.groovy
- src/services/ExperimentalDataCollectorImpl.groovy
- src/services/soot/SootScenario.groovy
Procura no repositório um arquivo pom.xml ou build.gradle para determinar qual o sistema de build do projeto e adapta o arquivo travis.yml para coletar a build e acordo. Além disso resolve bugs encontrados no processo de criar essa PR.
Resolve #53
> Adiciona o build por gradle

- src/services/ProjectProcessorImpl.groovy
Mudei para fazer essa tentativa individualmente para que não pare a execução completamente quando não conseguir ativar algum dos projetos, tentado executar os outros.
> Tentar ativar projetos no travis individualmente

- src/main/app/MiningFramework.groovy
- src/main/app/MiningWorker.groovy
- src/main/arguments/ArgsParser.groovy
- src/main/arguments/Arguments.groovy
> Adiciona opção de manter projetos depois da análise

- src/services/ExperimentalDataCollectorImpl.groovy
I checked the diffj output and i am using this substring to remove this specific case.
> Add condition to remove static blocks from analysis

- build.gradle
- src/main/arguments/ArgsParser.groovy
- src/test/unit/ArgsParserTest.groovy
I added unit tests for the **argsParser** class and achieved coverage of: 100% of the class, 88% of the methods and 92% of the code lines.
In addition, I made changes to the **argsParser** class to correct the following problems:
1. When an **outputFile** ending with '/' is sent the error is returned: 
```
No such property: dir for class: arguments.ArgsParser
groovy.lang.MissingPropertyException: No such property: dir for class: arguments.ArgsParser
```
2. Return `true` when sending an invalid date to the`validDate` method
3. upgrade to junit 5 while maintaining junit4 compatibility
4. add validation for "Invalid argument passed"
Resolves #95
> create unit tests for argParse class

- scripts/fetch_jars.py
> Fix get_github_releases call to consider github api pagination

- src/main/arguments/InputParser.groovy
- src/main/services/commitFilters/IsInCommitListFilter.groovy
- src/test/assets/invalidFile.csv
- src/test/assets/projectsTest.csv
- src/test/assets/separatorSemicolon.csv
- src/test/assets/withoutProjects.csv
- src/test/unit/InputParserTest.groovy
1. Added unit tests for the **InputParser** class
2. Added check for non-precessed input files
Resolves #97
> Feature/#97 - create unit tests for InputParser class 

- src/main/services/outputProcessors/soot/ConflictDetectionAlgorithm.groovy
- src/main/services/outputProcessors/soot/RunSootAnalysisOutputProcessor.groovy
- src/test/integration/fileTest/compare/data/soot-results.csv
This PR updates soot-analysis to 0.1.0 version and also fixes an error causing timeouts.
> Update soot analysis version and fix error causing timeouts

- src/main/services/outputProcessors/soot/README.md
- src/main/services/outputProcessors/soot/RunSootAnalysisOutputProcessor.groovy
- src/test/integration/fileTest/compare/data/soot-results.csv
This PR updates the soot-analysis jar to use the lastest version.
> Update soot-analysis to version 0.2.1

- src/main/services/outputProcessors/soot/RunSootAnalysisOutputProcessor.groovy
- src/test/integration/fileTest/compare/data/soot-results.csv
Adicionei OA inter e renomeei OA Intra
> feat: add OA inter

- src/main/services/dataCollectors/S3MMergesCollector/S3MRunner.groovy
This PR updates S3M's jar executable.
> S3M's jar update

- dependencies/csdiff.sh
- src/main/injectors/CSDiffModule.groovy
- src/main/services/commitFilters/MutuallyModifiedFilesCommitFilter.groovy
- src/main/services/dataCollectors/csDiffCollector/CSDiffCollector.groovy
- src/main/services/dataCollectors/csDiffCollector/CSDiffRunner.groovy
- src/main/services/dataCollectors/csDiffCollector/DataAnalyser.groovy
- src/main/services/dataCollectors/csDiffCollector/SpreadsheetBuilder.groovy
- src/main/services/mergeScenariosFilters/NonFastForwardMergeScenarioFilter.groovy
- src/main/services/outputProcessors/EmptyOutputProcessor.groovy
- src/main/services/projectProcessors/DummyProjectProcessor.groovy
- src/main/services/util/CSDiffMergeCommitSummary.groovy
- src/main/services/util/CSDiffMergeScenarioSummary.groovy
- src/main/services/util/MergeConflict.groovy
Esse MR cria o modulo de analise para o Custom Separators Diff (CSDiff).
> Add csdiff tool

- src/main/injectors/DynamicAnalysisConflictsDetectionModule.groovy
- src/main/injectors/StaticAnalysisConflictsDetectionModule.groovy
- src/main/services/outputProcessors/FetchBuildsOutputProcessor.groovy
- src/main/services/util/FetchBuildsScript.groovy
This PR adds the dynamic analysis conflicts detection module.
> Dynamic Analysis Module

- src/main/injectors/CSDiffModule.groovy
- src/main/services/commitFilters/NonFastForwardMergeCommitFilter.groovy
- src/main/services/dataCollectors/csDiffCollector/DataAnalyser.groovy
- src/main/services/mergeScenariosFilters/NonFastForwardMergeScenarioFilter.groovy
Renamings, optimizations and accurate documentation for the CSDiff study
> CSDiff study

- src/main/services/dataCollectors/csDiffCollector/SpreadsheetBuilder.groovy
- Add missing column
- Change column names to be more descriptive
> Fix column names on SpreadSheetBuilder

- requirements.txt
Adicionando dependências usadas no script que galileu adicionou para gerar os resultados em pdf
> feat: update requeriments

- input/LOI.csv
- scripts/generate_analysis_results.py
1. Corrigi o arquivo de entrada para LOI: alguns cenários estavam com o nome do método errado, usando ponto e vírgula em vez de vírgula, foi erro na geração do arquivo de CSV
2. Corrigi o algoritmo de relatório:
2.1. Antes: ele verificava um a um se tinha pelo menos um falso
2.2. Agora: agora criei uma lista pra fazer isso
> fix: fix count algorithms and report result

- requirements.txt
There is an error during the experiment execution
> Removing numexp

- README.md
- build.gradle
- src/main/app/Main.groovy
- src/main/arguments/ArgsParser.groovy
- src/main/arguments/Arguments.groovy
- src/main/resources/log4j2.properties
This PR adds log4j for better and more consistent logging across the application. It also adds a cli option `-log` or `--log-level` in order to customize the minimum level for showing logs.
> feat: Add logging with log4j

- build.gradle
- src/main/injectors/GenericMergeModule.groovy
- src/main/services/dataCollectors/GenericMerge/GenericMergeConfig.groovy
- src/main/services/dataCollectors/GenericMerge/MergeConflictsComparator.groovy
- src/main/services/dataCollectors/GenericMerge/MergeToolsComparator.groovy
- src/main/services/dataCollectors/GenericMerge/ScenarioLOCsCounter.groovy
- src/main/services/dataCollectors/GenericMerge/UnstructuredMergeCollector.groovy
- src/main/services/mergeScenariosFilters/NonFastForwardMergeScenarioFilter.groovy
- src/main/services/util/MergeConflict.groovy
- src/main/util/CsvUtils.groovy
This PR adds a Data Collector that will be used in the Generic Merge module experiment. Its responsibility is to check whether the results of jDime and Generic Merge are syntactically equivalent.
> feat: Add more Data Collectors for Generic Merge study

- src/main/arguments/Arguments.groovy
- src/main/injectors/MergirafAndSepMergeModule.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/DataAnalyser.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/MergeSummary.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/MergesCollector.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/SpreadsheetBuilder.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/mergeToolRunners/MergirafRunner.groovy
- src/main/services/dataCollectors/MergirafAndSepMergeCollector/mergeToolRunners/SepMergeRunner.groovy
- src/main/services/dataCollectors/S3MWithCSDiffCollector/mergeToolRunners/Diff3Runner.groovy
- src/main/services/util/MergeToolRunner.groovy
Adiciona o estudo do Mergiraf vs SepMerge ao projeto, levando em consideração os ajustes e features implementados no [PR anterior](https://github.com/spgroup/miningframework/pull/208).
> Estudo do Mergiraf vs SepMerge
